#
#  Indium - by SolexGames (GrowlyX)
#
settings:
  # This should be your discord bot token
  token: ""
  prefix: "-"
  status: "DO_NOT_DISTURB"
  activity: "www.solexgames.com"
  owner-id: "559497100296060939"
  # The default rank on your server
  server-default-rank: "Default"
  hex: "#ff06f3"
language:
  syncing:
    # The role which will be given on sync
    role: "Verified"
    # Channel name which will be monitored
    channel: "sync"
    # The player's discord display name once they are synced
    username-format: "[Verified] <playerName>"
  successful-sync:
    title: "**Synced**"
    description: "You've successfully synced your discord account to the account with the username: `<playerName>`!<nl><nl>You've also been given your **Verified** tag, which you can equip with the `/tags` command in-game!"
  already-synced:
    title: "**Already synced**"
    description: "You're already synced to an account!<nl><nl>Type `/unsync` in chat to unsync your account and rejoin to setup syncing again."
  invalid-code:
    title: "**Invalid code**"
    description: "I'm sorry, but that's not a valid code. Please double check your code or contact staff."
  panel:
    title: "**Account Syncing**"
    description: "Use `/sync` in-game to receive your account syncing code and use `-sync` in this channel to sync your discord account!"
    image-url: "https://cdn.discordapp.com/attachments/839431125196996618/841697784691687424/pvpbar-header.png"
