#
#  dRobot-RECODE - by GrowlyX
#
settings:
  token: "ODE5NjQwMjMzMDQ5ODQ5OTQz.YEpjcw.SrhxES9a4VQfFXBWTGbtq9sf54I"
  prefix: "-"
  status: "DO_NOT_DISTURB"
  activity: "eventis.club"
  owner-id: "559497100296060939"
  hex: "#ff06f3"
  sync-panel-bg: "https://cdn.discordapp.com/attachments/839431125196996618/841697784691687424/pvpbar-header.png
