#
#  dRobot-RECODE - by GrowlyX
#
settings:
  token: "ODE5NjQwMjMzMDQ5ODQ5OTQz.YEpjcw.SrhxES9a4VQfFXBWTGbtq9sf54I"
  prefix: "-"
  status: "DO_NOT_DISTURB"
  activity: "eventis.club"
  owner-id: "559497100296060939"
  support-role-name: "Staff"
  hex: "#ff06f3"
  admin-ids:
    - "266737992603795456"
activity-scroll:
  enabled: true
  strings:
    - "eventis.club"
    - "Watching your messages"
    - "Watching <online> Online"

